@startuml test222
title "Ravimiskeemi ravimi lisamine"

hide footbox

actor "Teenuse kasutaja" as you
participant "MedIN" as me

note left : loppkasutaja on sisestanud lisatava ravimi toimeainete või preparaadi info
you o-> me: ei 
me --> you: FHIR bundle

end 

@enduml