@startuml test222

hide footbox

actor "Teenuse kasutaja (TTO  klientsüsteem, TJT)" as you
participant "MedIN" as pu #DEE

group Päritakse patsient MPI viite alusel kehtiv ravimiskeem
you -> pu: puuy
pu --> you: FHIR Bundle
activate you
end


group Päritakse kehtivas ravimiskeemis olevaid koostoimeid
you -> pu: plaa
pu --> you: FHIR Bundle
activate pu
end

end

@enduml